[package]
name = "eth_stark_resolver"
version = "0.1.0"

[dependencies]
starknet = "2.3.1"
naming = { git = "https://github.com/starknet-id/naming", rev = "418030873ae254dd7c7cd11c37a3cb9c00c8e8cd" }
storage_read = { git = "https://github.com/starknet-id/storage_read_component", rev = "c6c69e15d34abfc39ac51dc21b96724e2e19ff31" }
encoder = { git = "https://github.com/starknet-id/encoder_component", rev = "78512bf6f0788513bc906941b328921e313be732" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false
